"""Type stubs for native Rust extension _multiloop_core."""

from typing import Any

class ThreadPoolClosedError(RuntimeError): ...

class AtomicMetrics:
    def __init__(self, num_threads: int) -> None: ...
    def inc_active(self, index: int) -> None: ...
    def dec_active(self, index: int) -> None: ...
    def get_active(self, index: int) -> int: ...
    def get_completed(self, index: int) -> int: ...
    def inc_global_pull(self, index: int) -> None: ...
    def add_global_pull(self, index: int, count: int) -> None: ...
    def get_global_pull(self, index: int) -> int: ...
    def inc_park(self, index: int) -> None: ...
    def get_park(self, index: int) -> int: ...
    def set_injection_queue_depth(self, index: int, depth: int) -> None: ...
    def get_injection_queue_depth(self, index: int) -> int: ...
    def inc_remote_schedule(self, index: int) -> None: ...
    def get_remote_schedule(self, index: int) -> int: ...

class NativeWorkerPool:
    def __init__(self, num_threads: int) -> None: ...
    def close(self) -> None: ...
    def set_metrics(self, metrics: AtomicMetrics) -> None: ...
    def is_closed(self) -> bool: ...
    def is_drained(self) -> bool: ...
    def push_global(self, task: Any) -> None: ...
    def push_local(self, index: int, task: Any) -> None: ...
    def pop_work(self, index: int) -> Any | None: ...

class Channel:
    def __init__(self, maxsize: int) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def try_send(self, item: Any) -> bool: ...
    def try_recv(self) -> tuple[bool, Any]: ...
    def qsize(self) -> int: ...

class RawAsyncChannel:
    def __init__(
        self,
        maxsize: int = ...,
        wake_fn: Any = ...,
        select_wake_fn: Any = ...,
    ) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def qsize(self) -> int: ...
    @property
    def maxsize(self) -> int: ...
    def empty(self) -> bool: ...
    def full(self) -> bool: ...
    def try_send(self, item: Any) -> bool: ...
    def try_recv(self) -> tuple[bool, Any]: ...
    def register_getter(self, loop: Any, fut: Any) -> tuple[bool, Any]: ...
    def unregister_getter(self, fut: Any) -> bool: ...
    def register_putter(self, loop: Any, fut: Any) -> bool: ...
    def unregister_putter(self, fut: Any) -> bool: ...
    def claim_put(self, item: Any) -> bool: ...
    def register_select_watcher(self, loop: Any, arbiter_fut: Any, channel_token: Any) -> bool: ...
    def unregister_select_watcher(self, fut: Any) -> bool: ...
    def forward_select_wakeup(self) -> None: ...
    def send_sync(self, item: Any, timeout: float | None = ...) -> None: ...
    def recv_sync(self, timeout: float | None = ...) -> Any: ...
    def getters_len(self) -> int: ...
    def putters_len(self) -> int: ...
    def notifiers_len(self) -> int: ...

class RawAsyncWaitGroup:
    def __init__(self) -> None: ...
    def add(self, delta: int) -> list[tuple[Any, Any]] | None: ...
    def done(self) -> list[tuple[Any, Any]] | None: ...
    def register_waiter(self, waiter: tuple[Any, Any]) -> bool: ...
    def unregister_waiter(self, fut: Any) -> bool: ...

class RawAsyncRWMutex:
    def __init__(self) -> None: ...
    def try_acquire_read(self) -> bool: ...
    def acquire_read_or_register(self, loop: Any, fut: Any) -> bool: ...
    def release_read(self) -> list[tuple[Any, Any]] | None: ...
    def try_acquire_write(self) -> bool: ...
    def acquire_write_or_register(self, loop: Any, fut: Any) -> bool: ...
    def release_write(self) -> list[tuple[Any, Any]] | None: ...
    def remove_waiter(
        self, loop: Any, fut: Any, is_writer: bool
    ) -> list[tuple[Any, Any]] | None: ...
    def snapshot(self) -> tuple[int, bool, int]: ...
